### ISSUE TITLE
4.3.3 not on MvnRepository

### ISSUE THREAD

**Issue by cf256** [googlemaps/android-maps-compose#524] opened 2024-02-09 10:59 UTC
Latest version is 4.3.2: https://central.sonatype.com/artifact/com.google.maps.android/maps-compose?smo=true, https://mvnrepository.com/artifact/com.google.maps.android/maps-compose

However latest GitHub release is 4.3.3

**Comment by risalfajar** [comment] 2024-02-12 15:24
Thanks, just confused of why my imports doesn't work

**Comment by kungufli** [comment] 2024-02-26 10:28
The issue is now fixed.

**Comment by wangela** [comment] 2024-02-27 19:12
Sorry for the delay folks! Our automated release process broke down and we had to manually release the artifact.

**Closed by wangela** 2024-02-27 19:12 UTC
Labels: type: bug, priority: p1
