### ISSUE TITLE
How to detect that Google Maps failed to load?

### ISSUE THREAD

**Issue by peterdk** [googlemaps/android-maps-compose#103] opened 2022-04-28 08:12 UTC
**Is your feature request related to a problem? Please describe.**
How can I handle the situation where Google Maps is not available on device?

 **Describe the solution you'd like**
A error state that indicates map failed to load.

I am trying to implement an error message for when the map SDK is not available (Tested on an emulator without google services).
It's not clear for me how to handle this, cause I don't see an error state variable. Maybe I am missing something, otherwise I would like to request that to be added.

**Comment by jpoehnelt** [comment] 2022-04-28 08:12
@peterdk Thank you for opening this issue. 🙏
Please check out these other resources that might be applicable:

- [Support Console](https://cloud.google.com/support/) - If you have a support contract.
- [Discord](https://discord.gg/9UpV862xZ9) - chat with other developers
- [StackOverflow](http://stackoverflow.com/questions/tagged/google-maps) - use the `google-maps` tag
- [Google Maps Platform issue trackers](https://developers.google.com/maps/support/#issue_tracker)


_This is an automated message, feel free to ignore._

**Comment by arriolac** [comment] 2022-05-04 23:38
Duplicate of #50

**Closed** 2022-05-05 19:53 UTC
Labels: duplicate, type: feature request
