### ISSUE TITLE
Add support to get the visible region

### ISSUE THREAD

**Issue by adrinieto** [googlemaps/android-maps-compose#48] opened 2022-02-27 20:14 UTC
Right now there is no way to get the bounds of the visible region. This can be accessed from `GoogleMap`: `googleMap.projection.visibleRegion`. 

https://developers.google.com/maps/documentation/android-sdk/reference/com/google/android/libraries/maps/model/VisibleRegion

This is key to allow interactivity with the map and support complex applications, for example, I need to make an API request just for the visible region bounds.

**Comment by jpoehnelt** [comment] 2022-02-27 20:14
@adrinieto Thank you for opening this issue. 🙏
Please check out these other resources that might be applicable:

- [Support Console](https://cloud.google.com/support/) - If you have a support contract.
- [Discord](https://discord.gg/9UpV862xZ9) - chat with other developers
- [StackOverflow](http://stackoverflow.com/questions/tagged/google-maps) - use the `google-maps` tag
- [Google Maps Platform issue trackers](https://developers.google.com/maps/support/#issue_tracker)


_This is an automated message, feel free to ignore._

**Comment by arriolac** [comment] 2022-03-03 16:27
Duplicate of #45

**Closed by arriolac** 2022-03-03 16:27 UTC
Labels: duplicate, type: feature request
