### ISSUE TITLE
android-maps-compose:2.11.4 IllegalArgumentException: Unmanaged descriptor in DefaultClusterRenderer

### ISSUE THREAD

**Issue by charlesbukenyaqvik** [googlemaps/android-maps-compose#316] opened 2023-05-02 19:54 UTC
Thanks for stopping by to let us know something could be better!

---
**PLEASE READ** 

If you have a support contract with Google, please create an issue in the [support console](https://cloud.google.com/support/). This will ensure a timely response. 

Discover additional support services for the Google Maps Platform, including developer communities, technical guidance, and expert support at the Google Maps Platform [support resources page](https://developers.google.com/maps/support/). 

If your bug or feature request is not related to this particular library, please visit the Google Maps Platform [issue trackers](https://developers.google.com/maps/support/#issue_tracker).

Check for answers on StackOverflow with the [google-maps](http://stackoverflow.com/questions/tagged/google-maps) tag.

---

Please be sure to include as much information as possible:

#### Environment details

1. Android-maps-compose:2.11.4
2. Pixel 6 pro API 33 android studio emulator, android studio Giraffe 
3. Android-maps-compose:2.11.4, android 

#### Steps to reproduce

This happens randomly after awhile playing around the map. zooming in and out and panning the map view. 
I have had to switch to MapEffect and implement CustomCluster renderer because of this. I t seems this is caused by some caching issues for markers
#### Code example

clusterItemContent = {
                            Surface(
                                Modifier
                                    .height(36.dp)
                                    .width(36.dp),
                                shape = CircleShape,
                                color = okayColor,
                                contentColor = Color.White,
                                border = BorderStroke(1.dp, white)
                            ) {
                                Box(contentAlignment = Alignment.Center) {
                                    Icon(
                              //this is a vector drawable icon, works well when it is working but then this crash happens
                                        painter = painterResource(id = R.drawable.icon_aed_pin),
                                        contentDescription = "AEd icon",
                                    )
                                }
                            }
                        }
                    )
# example
```

#### Stack trace
FATAL EXCEPTION: main
                                                                                                    Process: com.myapp.app, PID: 2821
                                                                                                    java.lang.IllegalArgumentException: Unmanaged descriptor
                                                                                                    	at com.google.maps.api.android.lib6.common.m.c(:com.google.android.gms.dynamite_mapsdynamite@225014044@22.50.14 (190400-0):0)
                                                                                                    	at com.google.maps.api.android.lib6.impl.w.c(:com.google.android.gms.dynamite_mapsdynamite@225014044@22.50.14 (190400-0):1)
                                                                                                    	at com.google.maps.api.android.lib6.impl.cy.u(:com.google.android.gms.dynamite_mapsdynamite@225014044@22.50.14 (190400-0):2)
                                                                                                    	at com.google.android.gms.maps.model.internal.p.ba(:com.google.android.gms.dynamite_mapsdynamite@225014044@22.50.14 (190400-0):42)
                                                                                                    	at fd.onTransact(:com.google.android.gms.dynamite_mapsdynamite@225014044@22.50.14 (190400-0):4)
                                                                                                    	at android.os.Binder.transact(Binder.java:1164)
                                                                                                    	at com.google.android.gms.internal.maps.zza.zzc(com.google.android.gms:play-services-maps@@18.1.0:2)
                                                                                                    	at com.google.android.gms.internal.maps.zzy.zzs(com.google.android.gms:play-services-maps@@18.1.0:3)
                                                                                                    	at com.google.android.gms.maps.model.Marker.setIcon(com.google.android.gms:play-services-maps@@18.1.0:2)
                                                                                                    	at com.google.maps.android.clustering.view.DefaultClusterRenderer.onClusterUpdated(DefaultClusterRenderer.java:972)
                                                                                                    	at com.google.maps.android.clustering.view.DefaultClusterRenderer$CreateMarkerTask.perform(DefaultClusterRenderer.java:1091)
                                                                                                    	at com.google.maps.android.clustering.view.DefaultClusterRenderer$CreateMarkerTask.access$1900(DefaultClusterRenderer.java:1027)
                                                                                                    	at com.google.maps.android.clustering.view.DefaultClusterRenderer$MarkerModifier.performNextTask(DefaultClusterRenderer.java:738)
                                                                                                    	at com.google.maps.android.clustering.view.DefaultClusterRenderer$MarkerModifier.handleMessage(DefaultClusterRenderer.java:710)
                                                                                                    	at android.os.Handler.dispatchMessage(Handler.java:106)
                                                                                                    	at android.os.Looper.loopOnce(Looper.java:201)
                                                                                                    	at android.os.Looper.loop(Looper.java:288)
                                                                                                    	at android.app.ActivityThread.main(ActivityThread.java:7872)
                                                                                                    	at java.lang.reflect.Method.invoke(Native Method)
                                                                                                    	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
                                                                                                    	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:936)
# example
```

Following these steps will guarantee the quickest resolution possible.

Thanks!

**Comment by wangela** [comment] 2023-05-02 19:56
If you would like to upvote the priority of this issue, please comment below or react with :+1: so we can see what is popular when we triage.
--------

@charlesbukenyaqvik Thank you for opening this issue. 🙏
Please check out these other resources that might help you get to a resolution in the meantime:

- [Check the issue tracker](https://developers.google.com/maps/support/#issue_tracker) - bugs and feature requests for Google Maps Platform APIs and SDKs
- [Open a support case](https://developers.google.com/maps/support#contact-maps-support) - Get 1:1 support in Cloud Console.
- [Discord](https://discord.gg/fHTDmZe9En) - chat with other developers
- [StackOverflow](http://stackoverflow.com/questions/tagged/google-maps) - use the `google-maps` tag


_This is an automated message, feel free to ignore._

**Comment by wangela** [comment] 2023-08-10 22:52
@charlesbukenyaqvik is this still happening to you in the latest version?

**Comment by wangela** [comment] 2023-08-11 19:01
Closing as possible duplicate of #332

**Closed by wangela** 2023-08-11 19:01 UTC
Labels: needs more info, type: bug, priority: p3

**Comment by charlesbukenyaqvik** [comment] 2023-08-22 09:25
@wangela I had to create my own CustomCluster renderer than I apply, had to many issues with your clustering composable

**Comment by wangela** [comment] 2023-08-22 17:09
@kikoso see comment above
