### ISSUE TITLE
Clear the map or Remove marker

### ISSUE THREAD

**Issue by rtippisetty** [googlemaps/android-maps-compose#98] opened 2022-04-19 06:06 UTC
**Is your feature request related to a problem? Please describe.**
I wanted to display 100's of markers dynamically as the map is dragged. During the process I have to remove (_clear the Map_) the existing markers and add new markers as and when the map center changes with new locations.

 **Describe the solution you'd like**
In order to achieve it I require either a handle to marker to remove it (like `marker.remove()`) or a handle to map to clear the entire map (like `map.clear()`). Solution can be returning a handle to google map via parameter in the method `onMapLoaded: () -> [Unit]`.
To remove a marker there could be a new lambda in `Marker`() function to return it a parameter.

 **Describe alternatives you've considered**
An alternative solution could be introducing a new state in `GoogleMap` function to set map clear state.

**Comment by jpoehnelt** [comment] 2022-04-19 06:06
@rtippisetty Thank you for opening this issue. 🙏
Please check out these other resources that might be applicable:

- [Support Console](https://cloud.google.com/support/) - If you have a support contract.
- [Discord](https://discord.gg/9UpV862xZ9) - chat with other developers
- [StackOverflow](http://stackoverflow.com/questions/tagged/google-maps) - use the `google-maps` tag
- [Google Maps Platform issue trackers](https://developers.google.com/maps/support/#issue_tracker)


_This is an automated message, feel free to ignore._

**Comment by NitroG42** [comment] 2022-04-19 12:26
I invite you to read the answer here : https://github.com/googlemaps/android-maps-compose/issues/91#issuecomment-1089079236
If I understand what you want correctly, you can already do it by managing the `Marker` composable. 
To do "I wanted to display 100's of markers dynamically" with Compose, you just need a list of markers as State, and then iterating on it creating Markers Composable. 
Any update on the list will remove markers not present and add the new markers.
It's a lot more convenient than previous API.

**Comment by barbeau** [comment] 2022-04-27 18:48
I'm going to close this as a duplicate of https://github.com/googlemaps/android-maps-compose/issues/91.

@rtippisetty Please take a look at that issue and if it doesn't resolve your question please comment there. Thanks!

**Closed by barbeau** 2022-04-27 18:48 UTC
Labels: type: question
