### ISSUE TITLE
Set custom content as UI buttons 

### ISSUE THREAD

**Issue by Psijic** [googlemaps/android-maps-compose#322] opened 2023-05-27 18:04 UTC
Currently to make custom buttons (zoom, location etc.), you need to make your overlay and disable defaults. But it could be possible to provide needed buttons as a composable context in options to the `Map`.

**Comment by wangela** [comment] 2023-08-10 22:51
Although this was filed first, marking this as duplicate of #340 and #339 since we are implemeting those separately and will close them one at a time.

**Closed by wangela** 2023-08-10 22:51 UTC
Labels: duplicate, type: feature request, priority: p2
