### ISSUE TITLE
Exposing GoogleMap.OnCameraMoveStartedListener "reason"

### ISSUE THREAD

**Issue by Bmahecha123** [googlemaps/android-maps-compose#104] opened 2022-04-29 00:47 UTC
I hooked up fusedLocationClient to cameraPositionState to keep current location regularly updated. I have some logic related to the `isMoving` flag. However I noticed that this flag is constantly toggling.

Could we expose OnCameraMoveStartedListener so I can check the reason as a flag instead? https://developers.google.com/android/reference/com/google/android/gms/maps/GoogleMap.OnCameraMoveStartedListener

This is currently not exposed. Thanks <3!

**Comment by jpoehnelt** [comment] 2022-04-29 00:47
@Bmahecha123 Thank you for opening this issue. 🙏
Please check out these other resources that might be applicable:

- [Support Console](https://cloud.google.com/support/) - If you have a support contract.
- [Discord](https://discord.gg/9UpV862xZ9) - chat with other developers
- [StackOverflow](http://stackoverflow.com/questions/tagged/google-maps) - use the `google-maps` tag
- [Google Maps Platform issue trackers](https://developers.google.com/maps/support/#issue_tracker)


_This is an automated message, feel free to ignore._

**Comment by arriolac** [comment] 2022-05-18 01:40
Is what your trying to do not doable with the current `isMoving` flag? Not sure what you're trying to achieve but you should be able to perform a computation using `LaunchedEffect` keyed on `isMoving`. If you can share more of your use case that would be helpful @Bmahecha123

**Comment by arriolac** [comment] 2022-05-18 15:51
Thanks for clarifying @barbeau . It looks like the library is swallowing the `reason` flag and should be exposed as a property to `CameraPositionState`. See: https://github.com/googlemaps/android-maps-compose/blob/main/maps-compose/src/main/java/com/google/maps/android/compose/MapUpdater.kt#L72

**Comment by Bmahecha123** [comment] 2022-05-18 15:59
Thank you for the clarification @barbeau !

Relying on `isMoving` is not trustworthy since this flag can switch between true/false many times depending on location updates (fractions of a latitude/longitude even if phone is stationary). Relying on `reason` is more reliable since I can filter based on user based movement or camera updates by the native client.

**Comment by barbeau** [comment] 2022-05-18 18:16
Thanks @arriolac, that makes sense. I can try tackling this. My plan would be to finish the work in PR https://github.com/googlemaps/android-maps-compose/pull/94 that adds more examples in the app, and then add this feature along with a sample implementation in the demo app.

**Comment by barbeau** [comment] 2022-05-23 21:38
I'm actually realizing that this issue is a duplicate of https://github.com/googlemaps/android-maps-compose/issues/49, so I'm going to close this in favor of that because it's older. So please upvote https://github.com/googlemaps/android-maps-compose/issues/49 if you're following this issue and haven't seen https://github.com/googlemaps/android-maps-compose/issues/49 yet.

**Closed by barbeau** 2022-05-23 21:38 UTC
Labels: type: feature request, priority: p2
