### ISSUE TITLE
RFC: Add support for clustering

### ISSUE THREAD

**Issue by spoelt** [googlemaps/android-maps-compose#44] opened 2022-02-21 14:00 UTC
Do you plan on adding clustering to the Compose version of Google Maps? I tried making the switch from `AndroidView({ MapView() })` to the new Composable function but struggle to implement the `ClusterManager` given that I cannot directly reference the map as an input parameter when instantiating the `ClusterManager`.
(... and thank you for giving us this awesome Composable in the first place 🙏)

**Comment by jpoehnelt** [comment] 2022-02-21 14:01
@spoelt Thank you for opening this issue. 🙏
Please check out these other resources that might be applicable:

- [Support Console](https://cloud.google.com/support/) - If you have a support contract.
- [Discord](https://discord.gg/9UpV862xZ9) - chat with other developers
- [StackOverflow](http://stackoverflow.com/questions/tagged/google-maps) - use the `google-maps` tag
- [Google Maps Platform issue trackers](https://developers.google.com/maps/support/#issue_tracker)


_This is an automated message, feel free to ignore._

**Comment by arriolac** [comment] 2022-03-01 20:50
Yes, I would like to add this! Adding clustering support isn't quite that simple though as Maps Compose entirely manages the underlying `GoogleMap`. I've summarized my thoughts on this in [this comment](https://github.com/googlemaps/android-maps-compose/issues/28#issuecomment-1041946666)

**Comment by StephenVinouze** [comment] 2022-04-21 08:35
Can't this be achieved already with the [Maps Utils Library](https://github.com/googlemaps/android-maps-utils)? Since that's where you get the `ClusterManager`. I haven't tried yet but I naively thought Map Compose would interact with this lib the same way as with Views 🤔

**Comment by StephenVinouze** [comment] 2022-04-21 08:41
Hmm I see, the `ClusterManager` needs a map as an argument. Never mind my previous comment then 😅

**Comment by NitroG42** [comment] 2022-04-25 13:54
I think I'll provide some more info on why the cluster manager is needed:
Right now, trying to display a high number of marker on the Maps will make the render freezes for a few seconds
with +500 (+1000) markers, using a simple:
```
poi.forEach {
    Marker(...)
}
```
I think the only solution for now is either display less (based on the viewport for example, restrict to a certain amount or distance), or make an "almost" clustering implementation outside of the composition (based on the viewport, and make "cluster" markers on the fly by grouping your markers based on a distance or lat/long. It might be long to make that of course)

**Comment by sajithlaldev** [comment] 2022-04-26 17:07
It was a nice feature in Native android. Now I am switched to Jetpack and screwed with my project. :( Hope this will be added soon

**Comment by barbeau** [comment] 2022-04-26 17:33
@sajithlaldev maps-compose doesn't yet support clustering, but note that if the rest of your project is written using Compose you can still use the normal Android Maps SDK within your project by using the Compose Interoperability APIs:
https://developer.android.com/jetpack/compose/interop/interop-apis#views-in-compose

So if clustering is critical to you I'd recommend sticking with the normal Maps SDK for now and using compose interop solution, which should work even if the rest of your app is written in Compose.

**Comment by sajithlaldev** [comment] 2022-04-26 17:38
Compose Interoperability APIs this would be nice. thanks for the info @barbeau

**Comment by Psijic** [comment] 2022-05-06 07:37
It looks like the original clustering / layers where made with a "difficult" code/architecture and now should be implemented from scratch to Compose maps. Maybe it'll add some better code structure and performance but currently is it possible to make clusters using custom markers images? Like you add a marker with a circle image and it's really a cluster.

**Comment by psteiger** [comment] 2022-05-06 19:46
@Psijic as an user of the current clustering library, I agree it begs for a complete rewrite in Compose mindset.

Those are my superficial thoughts on this matter:

1) Given a set of (x,y) points, a set of clusters must be generated, where a cluster is itself a (x,y) point but holds a set of 1 or more (x,y) points, representing the original points it is clustering. The x,y coordinates of the cluster is some kind of median between all x and all y of the original points.

2) Every time zoom changes, clusters must be recalculated. If the new zoom makes the points in the cluster not close enough for clustering, they should individually animate from the cluster position to the original position. Conversely, if the new zoom makes the points too close together, they should animate towards the cluster.

3) clicking on a clustering zooms in just enough so that the cluster destructures into its individual items.

Before we have a proper library for that, I'm thinking maybe this computation can be done in ViewModel, assuming the ViewModel stores the complete set of Items and the camera position/zoom. Thinking in `Flow` or `MutableState`, looks like it would be possible to combine the `CameraPosition` and the `List<Item>`, resulting in a `List<ClusterItem>` where `ClusterItem` owns a (x,y) position, an image, and N items the cluster is representing.

The animation part sounds tricky.

**Comment by newmanw** [comment] 2022-05-29 23:56
Adding first class clustering would be amazing. Very surprised Apple has clustering support built into the SDK and Google does not.

**Comment by thekingrenz23** [comment] 2022-06-05 06:54
clustering should be part of the next milestone I don't know why google is not prioritizing this its such a critical part of performance

**Comment by jeffnyauke** [comment] 2022-06-07 08:56
Do we have a timeline for this?

**Comment by ColtonIdle** [comment] 2022-06-07 11:43
👀 https://github.com/googlemaps/android-maps-compose/issues/135

**Comment by Shusshu** [comment] 2022-06-21 12:02
https://github.com/googlemaps/android-maps-compose/pull/140
🎉

**Comment by barbeau** [comment] 2022-06-21 16:24
As @Shusshu pointed out above, PR https://github.com/googlemaps/android-maps-compose/pull/140 has been merged which adds an experimental `MapEffect` composable which exposes the `GoogleMap` object that enables a workaround for clustering support.

See the new `MapClusteringActivity` in the demo app for a demo:
https://github.com/googlemaps/android-maps-compose/blob/main/app/src/main/java/com/google/maps/android/compose/MapClusteringActivity.kt#L28

**Comment by thekingrenz23** [comment] 2022-09-15 03:59
I am using the sample clustering using MapEffect but the info window of the markers are not kept open when navigating back to the map. How can i solve that?

**Comment by Psijic** [comment] 2023-01-03 09:43
Is there any custom-made clustering? I suppose, all the layout features unsupported now?

**Comment by ColtonIdle** [comment] 2023-01-05 20:57
@Psijic I don't work on maps compose, but I don't understand your question?
i have clustering working with compose. what do you mean by custom-made clustering?

**Comment by Psijic** [comment] 2023-01-06 07:11
@ColtonIdle I mean, half a year ago clustering wasn't available in Compose Google Maps.  How did you enable it here? 
` GoogleMap(content = content)`
Or you added old xml-based maps for clustering in your Compose layer?

**Comment by StephenVinouze** [comment] 2023-01-06 17:56
They made a workaround to let you access the `map` instance you need to use the `ClusterManager` from the util library. It works fine, with some limitations – it's marked as experimental. Everything is mentioned above along with the documentation: https://github.com/googlemaps/android-maps-compose#obtaining-access-to-the-raw-googlemap-experimental.
With that approach, you can now use clusterization while keeping a full compose.

**Comment by Psijic** [comment] 2023-01-06 18:00
It's something good. Does it have the close to Compose performance or it updates 60 FPS?

**Comment by StephenVinouze** [comment] 2023-01-06 18:01
I cannot say about benchmarks but on my side, it runs pretty smoothly so far :)

**Comment by ColtonIdle** [comment] 2023-01-10 15:49
Same here. I've used the new method with success. No more android view!

**Comment by thekingrenz23** [comment] 2023-01-14 12:10
One thing I can say is performance really bad

**Comment by ColtonIdle** [comment] 2023-01-24 19:09
@basurahan no perf issues here (in either debug or release builds). Do you have a repository you can put up to reproduce?

**Comment by basurahan** [comment] 2023-01-24 21:54
Really ? @ColtonIdle the initial loading of the map is really bad I doubt you don't have performance issues

**Comment by wangela** [comment] 2023-01-25 00:57
We'd love for folks interested in this issue to take a look at the draft PR #258 and comment on whether that would work better for you. Feel free to make suggestions as well. We'll leave it open for at least a week to provide some time for comment.

**Closed** 2023-02-16 20:25 UTC
Labels: type: feature request, priority: p1
