### ISSUE TITLE
How to use Clusters

### ISSUE THREAD

**Issue by ChoungYoung** [googlemaps/android-maps-compose#54] opened 2022-03-04 03:18 UTC
How to use clustermanager and clusteitem, It seems I can't get map

**Comment by jpoehnelt** [comment] 2022-03-04 03:18
@ChoungYoung Please take a moment to fill out [this short survey](https://forms.gle/wYuzN6UibnFj7ZL29). Thank you!

_This is an automated message, feel free to ignore._

**Comment by arriolac** [comment] 2022-03-04 03:21
Duplicate of #44

**Closed by arriolac** 2022-03-04 03:21 UTC
Labels: duplicate, type: feature request
