### ISSUE TITLE
Add documentation for GoogleMap inside scrolling column/Lazy Column

### ISSUE THREAD

**Issue by ManojMM026** [googlemaps/android-maps-compose#78] opened 2022-03-25 15:11 UTC
Please include more samples which has nested scrolling along with map view.

**Comment by jpoehnelt** [comment] 2022-03-25 15:11
@ManojMM026 Thank you for opening this issue. 🙏
Please check out these other resources that might be applicable:

- [Support Console](https://cloud.google.com/support/) - If you have a support contract.
- [Discord](https://discord.gg/9UpV862xZ9) - chat with other developers
- [StackOverflow](http://stackoverflow.com/questions/tagged/google-maps) - use the `google-maps` tag
- [Google Maps Platform issue trackers](https://developers.google.com/maps/support/#issue_tracker)


_This is an automated message, feel free to ignore._

**Comment by barbeau** [comment] 2022-04-05 16:41
I haven't tried this myself, but [here](https://github.com/googlemaps/android-maps-compose/issues/14) and [on Discord](https://discordapp.com/channels/676948200904589322/939194796138975263/949635746870996993) this solution was recommended:

```kotlin
cameraPositionState: Column(
    .verticalScroll(rememberScrollState(), enabled = !cameraPositionState.isMoving)
)
```

Please let me know if that works!

**Comment by thekingrenz23** [comment] 2022-04-09 23:00
> I haven't tried this myself, but [here](https://github.com/googlemaps/android-maps-compose/issues/14) and [on Discord](https://discordapp.com/channels/676948200904589322/939194796138975263/949635746870996993) this solution was recommended:
> 
> ```kotlin
> cameraPositionState: Column(
>     .verticalScroll(rememberScrollState(), enabled = !cameraPositionState.isMoving)
> )
> ```
> 
> Please let me know if that works!

This solution does not work  as @mistralaix mentioned

**Comment by barbeau** [comment] 2022-04-12 21:43
>Now we can scroll vertically but only if we start moving the camera horizontally, then we can move the camera vertically (good).
However, if we try to start moving the camera vertically, then the cameraPositionState.isMoving is not changing, the scroll from the column looks like to take the event first. (bad)

I can confirm the above behavior for the ` enabled = !cameraPositionState.isMoving)` code. 

I put together a simple example `ScrollingMapActivity` to test in this branch that exhibits this behavior:
https://github.com/googlemaps/android-maps-compose/tree/sean/scroll-example

**Comment by barbeau** [comment] 2022-06-06 14:12
PR https://github.com/googlemaps/android-maps-compose/pull/94 has been merged, which adds a `MapInColumnActivity` demo for the map inside a scrolling column:
https://github.com/googlemaps/android-maps-compose/blob/main/app/src/main/java/com/google/maps/android/compose/MapInColumnActivity.kt

![image](https://user-images.githubusercontent.com/928045/172177793-e0b461b4-164c-4ec9-af77-a06e3925e560.png)

I'm going to close this issue out, but please take a look at that and let me know if you have any questions!

**Closed as completed by barbeau** 2022-06-06 14:12 UTC
Labels: type: feature request, priority: p3
